name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    
    env:
      AMAZON_EMAIL: ${{ secrets.AMAZON_EMAIL }}
      AMAZON_PASSWORD: ${{ secrets.AMAZON_PASSWORD }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # or '7.0.x' based on your project

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Run Selenium Tests
        run: dotnet test --no-build --verbosity normal

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: TestReport
          path: Reports/TestReport.html
